version: '3'

services:
  app:
    build:
      context: ../.
      dockerfile: ./build/app/Dockerfile
    container_name: app
    restart: on-failure
    ports: 
      - ${APP_PORT}:${APP_PORT}
    networks:
      - image-previewer

networks:
  image-previewer:
