version: '3'

services:
  integration-app:
    build:
      context: ../.
      dockerfile: ./build/tests/app/Dockerfile
    networks:
      - integration
    depends_on:
      - remote-nginx
  remote-nginx:
    build:
      context: ../.
      dockerfile: ./build/tests/nginx/Dockerfile
    networks:
      - integration

networks:
  integration:
    driver: bridge
